name: 'Action to update GitHub Action documentation'
description: 'Update docuemntation in the README file for a GitHub Action based on the action.yml.'
author: 'Niek Palm'

branding:
  icon: book-open
  color: purple

inputs:
  readme:
    description: 'Readme file to update.'
    required: false
    default: README.md
  actionFile:
    description: 'The action definition file.'
    required: false
    deprecationMessage: 'This input is replaced by sourceFile'
  sourceFile:
    description: 'The action or workflow definition file.'
    required: false
    default: action.yml
  includeNameHeader:
    description: 'Include the name header in the updated readme.'
    required: false
    default: true
  tocLevel:
    description: 'TOC level used for the headers. The `includeNameHeader` input is influecing the TOC level, setting `includeNameHeader` to true will increase the TOC level by 1.'
    required: false
    default: 2
  lineBreaks:
    description: 'Line breaks to be used in updated readme (LF, CR or CRLF).'
    required: false
    default: LF

runs:
  using: 'node20'
  main: 'dist/index.js'
