name: 'Action to update GitHub Action documentation'
description: 'Update docuemntation in the README file for a GitHub Action based on the action.yml.'
author: 'Niek Palm'

branding:
  icon: book-open
  color: purple

inputs:
  readme:
    description: 'Readme file to update.'
    required: false
    default: README.md
  actionFile: 
    description: 'THe action definition file.'
    required: false
    default: action.yml
  tocLevel:
    description: "TOC level used for the headers."
    required: false
    default: 2
  lineBreaks:
    description: "Line breaks to be used in updated readme (LF|CR|CRLF)."
    required: false
    default: LF

runs:
  using: 'node20'
  main: 'dist/index.js'